import type { Formulation } from '../types'

const T_WINDOW = {
  id: 'eugonadal-m',
  label: 'Range eugonadico maschile',
  low: 300,
  high: 1000,
  unit: 'ng/dL' as const
}
const E2_WINDOW = {
  id: 'e2-f-follicular',
  label: 'E2 (orientativo, fase follicolare)',
  low: 30,
  high: 120,
  unit: 'pg/mL' as const
}
const P4_WINDOW = {
  id: 'p4-luteal',
  label: 'Progesterone luteale (orientativo)',
  low: 5,
  high: 25,
  unit: 'ng/mL' as const
}

type Draft = Partial<Formulation> &
  Pick<
    Formulation,
    | 'id'
    | 'compoundId'
    | 'name'
    | 'cluster'
    | 'analyte'
    | 'analyteLabel'
    | 'route'
    | 'tHalfDays'
    | 'tMaxDays'
    | 'doseRef'
    | 'cmaxRef'
    | 'nativeUnit'
    | 'typicalDoses'
    | 'defaultDose'
    | 'defaultFrequencyId'
  >

function F(d: Draft): Formulation {
  return {
    model: 'bateman',
    evidence: 'B',
    regulatory: 'authorized',
    doseUnit: 'mg',
    bioavailability: 1,
    defaultDurationDays: 84,
    sources: d.sources ?? [],
    ...d
  }
}

const T_MW = 288.42

export const FORMULATIONS: Formulation[] = [
  F({
    id: 'test-suspension',
    compoundId: 'testosterone',
    name: 'Testosterone base (sospensione)',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 0.4,
    tMaxDays: 0.08,
    doseRef: 50,
    cmaxRef: 1800,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: T_MW,
    yieldFraction: 1,
    typicalDoses: [25, 50, 75],
    defaultDose: 50,
    defaultFrequencyId: 'ed',
    defaultDurationDays: 28,
    window: T_WINDOW,
    evidence: 'B',
    sources: ['Behre & Nieschlag, Testosterone 2012']
  }),
  F({
    id: 'test-propionate',
    compoundId: 'testosterone',
    name: 'Testosterone propionato',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 0.8,
    tMaxDays: 0.6,
    doseRef: 50,
    cmaxRef: 1160,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 344.5,
    yieldFraction: 0.84,
    typicalDoses: [25, 50, 75, 100],
    defaultDose: 50,
    defaultFrequencyId: 'eod',
    defaultDurationDays: 56,
    window: T_WINDOW,
    evidence: 'A',
    sources: ['Behre HM et al. — t½ 0.8 d, MRT 1.5 d']
  }),
  F({
    id: 'test-phenylpropionate',
    compoundId: 'testosterone',
    name: 'Testosterone fenilpropionato',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 1.5,
    tMaxDays: 1.0,
    doseRef: 60,
    cmaxRef: 900,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 420.6,
    yieldFraction: 0.69,
    typicalDoses: [30, 60, 100],
    defaultDose: 60,
    defaultFrequencyId: 'e3d',
    window: T_WINDOW,
    evidence: 'B',
    sources: ['Componente Sustanon; t½ apparente ~1.5 d']
  }),
  F({
    id: 'test-isocaproate',
    compoundId: 'testosterone',
    name: 'Testosterone isocaproato',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 4.0,
    tMaxDays: 1.5,
    doseRef: 60,
    cmaxRef: 850,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 386.6,
    yieldFraction: 0.75,
    typicalDoses: [60, 100],
    defaultDose: 60,
    defaultFrequencyId: 'weekly',
    window: T_WINDOW,
    evidence: 'B',
    sources: ['Componente Sustanon; t½ apparente ~4 d']
  }),
  F({
    id: 'test-enanthate',
    compoundId: 'testosterone',
    name: 'Testosterone enantato',
    brand: 'Testoviron Depot',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 4.5,
    tMaxDays: 1.5,
    doseRef: 250,
    cmaxRef: 1136,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 400.6,
    yieldFraction: 0.72,
    vialMgPerMl: 250,
    typicalDoses: [50, 75, 100, 125, 200, 250],
    defaultDose: 100,
    defaultFrequencyId: 'weekly',
    window: T_WINDOW,
    evidence: 'A',
    sources: ['Behre & Nieschlag: t½ 4.5 d, MRT 8.5 d, Cmax ~39 nmol/L dopo 250 mg']
  }),
  F({
    id: 'test-cypionate',
    compoundId: 'testosterone',
    name: 'Testosterone cipionato',
    brand: 'Depo-Testosterone',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 5.0,
    tMaxDays: 1.8,
    doseRef: 200,
    cmaxRef: 909,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 412.6,
    yieldFraction: 0.7,
    vialMgPerMl: 200,
    typicalDoses: [50, 75, 100, 150, 200],
    defaultDose: 100,
    defaultFrequencyId: 'weekly',
    window: T_WINDOW,
    evidence: 'A',
    sources: ['PK simile all’enantato (Nieschlag). FDA label 50–400 mg ogni 2–4 sett']
  }),
  F({
    id: 'test-decanoate',
    compoundId: 'testosterone',
    name: 'Testosterone decanoato',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 7.5,
    tMaxDays: 2.5,
    doseRef: 100,
    cmaxRef: 700,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 442.7,
    yieldFraction: 0.65,
    typicalDoses: [100, 200],
    defaultDose: 100,
    defaultFrequencyId: 'e14d',
    window: T_WINDOW,
    evidence: 'B',
    sources: ['Componente Sustanon; t½ apparente ~7.5 d']
  }),
  F({
    id: 'test-undecanoate-castor',
    compoundId: 'testosterone',
    name: 'Testosterone undecanoato IM (olio di ricino)',
    brand: 'Nebido / Aveed',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 33.9,
    tMaxDays: 11.4,
    doseRef: 1000,
    cmaxRef: 920,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 456.7,
    yieldFraction: 0.63,
    vialMgPerMl: 250,
    typicalDoses: [750, 1000],
    defaultDose: 1000,
    defaultFrequencyId: 'e84d',
    defaultDurationDays: 365,
    window: T_WINDOW,
    evidence: 'A',
    sources: [
      'JCEM 2004 Schubert et al. TU 1000 mg; t½ 33.9 d olio di ricino',
      'Bayer Nebido PI'
    ]
  }),
  F({
    id: 'test-undecanoate-teaseed',
    compoundId: 'testosterone',
    name: 'Testosterone undecanoato IM (tea seed)',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 20.9,
    tMaxDays: 13,
    doseRef: 1000,
    cmaxRef: 890,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 456.7,
    yieldFraction: 0.63,
    typicalDoses: [1000],
    defaultDose: 1000,
    defaultFrequencyId: 'e70d',
    defaultDurationDays: 365,
    window: T_WINDOW,
    evidence: 'A',
    sources: ['Behre: t½ 20.9 d, MRT 34.9 d in tea seed oil']
  }),
  F({
    id: 'test-undecanoate-oral',
    compoundId: 'testosterone',
    name: 'Testosterone undecanoato orale',
    brand: 'Andriol / Jatenzo',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'oral',
    tHalfDays: 0.07,
    tMaxDays: 0.2,
    lagDays: 0.1,
    doseRef: 40,
    cmaxRef: 500,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 456.7,
    yieldFraction: 0.63,
    bioavailability: 0.07,
    typicalDoses: [40, 80, 158, 237],
    defaultDose: 80,
    defaultFrequencyId: 'bid',
    defaultDurationDays: 84,
    window: T_WINDOW,
    evidence: 'A',
    notes: 'Assorbimento linfatico, alta variabilità, da assumere con grassi.',
    sources: ['t½ ~1.6 h, MRT 3.7 h (Nieschlag)']
  }),
  F({
    id: 'test-gel-50',
    compoundId: 'testosterone',
    name: 'Testosterone gel 1–1,62%',
    brand: 'Testogel / AndroGel',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'td',
    model: 'zero-order',
    zeroOrderHours: 20,
    tHalfDays: 0.5,
    tMaxDays: 0.3,
    doseRef: 50,
    cmaxRef: 480,
    nativeUnit: 'ng/dL',
    yieldFraction: 1,
    typicalDoses: [20, 25, 40, 50, 60, 80],
    defaultDose: 50,
    defaultFrequencyId: 'ed',
    window: T_WINDOW,
    evidence: 'A',
    sources: ['AndroGel / Testogel SmPC; Cavg in range eugonadico a 50 mg/die']
  }),
  F({
    id: 'test-patch',
    compoundId: 'testosterone',
    name: 'Testosterone cerotto',
    brand: 'Androderm',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'td',
    model: 'zero-order',
    zeroOrderHours: 24,
    tHalfDays: 0.4,
    tMaxDays: 0.35,
    doseRef: 4,
    cmaxRef: 550,
    nativeUnit: 'ng/dL',
    typicalDoses: [2, 4, 6],
    defaultDose: 4,
    defaultFrequencyId: 'ed',
    window: T_WINDOW,
    evidence: 'A',
    sources: ['Androderm label']
  }),
  F({
    id: 'test-nasal',
    compoundId: 'testosterone',
    name: 'Testosterone nasale',
    brand: 'Natesto',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'nasal',
    tHalfDays: 0.04,
    tMaxDays: 0.03,
    doseRef: 11,
    cmaxRef: 800,
    nativeUnit: 'ng/dL',
    typicalDoses: [11],
    defaultDose: 11,
    defaultFrequencyId: 'tid',
    window: T_WINDOW,
    evidence: 'A',
    sources: ['Natesto USPI; picco rapido, t½ breve']
  }),
  F({
    id: 'test-sustanon-250',
    compoundId: 'testosterone',
    name: 'Sustanon 250',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 7,
    tMaxDays: 1.2,
    doseRef: 250,
    cmaxRef: 1850,
    nativeUnit: 'ng/dL',
    yieldFraction: 0.68,
    typicalDoses: [125, 250],
    defaultDose: 250,
    defaultFrequencyId: 'e21d',
    window: T_WINDOW,
    evidence: 'A',
    blendOf: [
      { formulationId: 'test-propionate', doseMg: 30 },
      { formulationId: 'test-phenylpropionate', doseMg: 60 },
      { formulationId: 'test-isocaproate', doseMg: 60 },
      { formulationId: 'test-decanoate', doseMg: 100 }
    ],
    sources: ['Sustanon SmPC: 30/60/60/100 mg per mL']
  }),
  F({
    id: 'test-omnadren',
    compoundId: 'testosterone',
    name: 'Omnadren 250',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 7,
    tMaxDays: 1.2,
    doseRef: 250,
    cmaxRef: 1850,
    nativeUnit: 'ng/dL',
    yieldFraction: 0.68,
    typicalDoses: [250],
    defaultDose: 250,
    defaultFrequencyId: 'e21d',
    window: T_WINDOW,
    evidence: 'B',
    blendOf: [
      { formulationId: 'test-propionate', doseMg: 30 },
      { formulationId: 'test-phenylpropionate', doseMg: 60 },
      { formulationId: 'test-isocaproate', doseMg: 60 },
      { formulationId: 'test-caproate', doseMg: 100 }
    ],
    sources: ['Blend analogo a Sustanon (caproato al posto del decanoato)']
  }),
  F({
    id: 'test-caproate',
    compoundId: 'testosterone',
    name: 'Testosterone caproato',
    cluster: 'testosterone',
    analyte: 'testosterone',
    analyteLabel: 'Testosterone',
    route: 'im',
    tHalfDays: 6.3,
    tMaxDays: 2.2,
    doseRef: 100,
    cmaxRef: 750,
    nativeUnit: 'ng/dL',
    parentMw: T_MW,
    esterMw: 386.6,
    yieldFraction: 0.75,
    typicalDoses: [100],
    defaultDose: 100,
    defaultFrequencyId: 'e14d',
    window: T_WINDOW,
    evidence: 'C',
    sources: ['Estere Omnadren; PK estrapolata']
  }),
  F({
    id: 'nandrolone-decanoate',
    compoundId: 'nandrolone',
    name: 'Nandrolone decanoato',
    brand: 'Deca-Durabolin',
    cluster: 'androgens',
    analyte: 'nandrolone',
    analyteLabel: 'Nandrolone',
    route: 'im',
    tHalfDays: 7.5,
    tMaxDays: 2.5,
    doseRef: 100,
    cmaxRef: 4.2,
    nativeUnit: 'ng/mL',
    yieldFraction: 0.64,
    typicalDoses: [25, 50, 100, 200],
    defaultDose: 50,
    defaultFrequencyId: 'e14d',
    evidence: 'A',
    regulatory: 'off-label',
    sources: ['Wijnand et al. nandrolone decanoate PK']
  }),
  F({
    id: 'nandrolone-pp',
    compoundId: 'nandrolone',
    name: 'Nandrolone fenilpropionato',
    brand: 'Durabolin / NPP',
    cluster: 'androgens',
    analyte: 'nandrolone',
    analyteLabel: 'Nandrolone',
    route: 'im',
    tHalfDays: 1.5,
    tMaxDays: 1.0,
    doseRef: 50,
    cmaxRef: 3.5,
    nativeUnit: 'ng/mL',
    yieldFraction: 0.67,
    typicalDoses: [25, 50],
    defaultDose: 50,
    defaultFrequencyId: 'e3d',
    evidence: 'B',
    regulatory: 'off-label',
    sources: ['t½ apparente ~1.5 d']
  }),
  F({
    id: 'dht-gel',
    compoundId: 'dht',
    name: 'Diidrotestosterone gel',
    brand: 'Andractim',
    cluster: 'androgens',
    analyte: 'dht',
    analyteLabel: 'DHT',
    route: 'td',
    model: 'zero-order',
    zeroOrderHours: 18,
    tHalfDays: 0.5,
    tMaxDays: 0.25,
    doseRef: 125,
    cmaxRef: 8,
    nativeUnit: 'ng/mL',
    typicalDoses: [50, 125, 250],
    defaultDose: 125,
    defaultFrequencyId: 'ed',
    evidence: 'B',
    sources: ['Andractim; DHT transdermico']
  }),
  F({
    id: 'mesterolone',
    compoundId: 'mesterolone',
    name: 'Mesterolone',
    brand: 'Proviron',
    cluster: 'androgens',
    analyte: 'mesterolone',
    analyteLabel: 'Mesterolone',
    route: 'oral',
    tHalfDays: 0.5,
    tMaxDays: 0.08,
    doseRef: 25,
    cmaxRef: 120,
    nativeUnit: 'ng/dL',
    typicalDoses: [25, 50],
    defaultDose: 25,
    defaultFrequencyId: 'bid',
    evidence: 'B',
    sources: ['Proviron SmPC']
  }),
  F({
    id: 'oxandrolone',
    compoundId: 'oxandrolone',
    name: 'Oxandrolone',
    brand: 'Anavar',
    cluster: 'androgens',
    analyte: 'oxandrolone',
    analyteLabel: 'Oxandrolone',
    route: 'oral',
    tHalfDays: 0.4,
    tMaxDays: 0.04,
    doseRef: 10,
    cmaxRef: 50,
    nativeUnit: 'ng/mL',
    typicalDoses: [2.5, 5, 10],
    defaultDose: 5,
    defaultFrequencyId: 'bid',
    evidence: 'A',
    regulatory: 'off-label',
    sources: ['t½ ~9–10 h; uso clinico wasting']
  }),
  F({
    id: 'e2-oral',
    compoundId: 'estradiol',
    name: 'Estradiolo micronizzato orale',
    cluster: 'estrogens',
    analyte: 'estradiol',
    analyteLabel: 'Estradiolo',
    route: 'oral',
    tHalfDays: 0.7,
    tMaxDays: 0.2,
    doseRef: 2,
    cmaxRef: 80,
    nativeUnit: 'pg/mL',
    typicalDoses: [0.5, 1, 2],
    defaultDose: 1,
    defaultFrequencyId: 'ed',
    window: E2_WINDOW,
    evidence: 'A',
    sources: ['Kuhl H. Pharmacology of estrogens']
  }),
  F({
    id: 'e2-valerate-oral',
    compoundId: 'estradiol',
    name: 'Estradiolo valerato orale',
    brand: 'Progynova',
    cluster: 'estrogens',
    analyte: 'estradiol',
    analyteLabel: 'Estradiolo',
    route: 'oral',
    tHalfDays: 0.8,
    tMaxDays: 0.25,
    doseRef: 2,
    cmaxRef: 70,
    nativeUnit: 'pg/mL',
    typicalDoses: [1, 2],
    defaultDose: 2,
    defaultFrequencyId: 'ed',
    window: E2_WINDOW,
    evidence: 'A',
    sources: ['Progynova SmPC']
  }),
  F({
    id: 'e2-gel',
    compoundId: 'estradiol',
    name: 'Estradiolo gel',
    brand: 'EstroGel / Sandrena / Oestrogel',
    cluster: 'estrogens',
    analyte: 'estradiol',
    analyteLabel: 'Estradiolo',
    route: 'td',
    model: 'zero-order',
    zeroOrderHours: 18,
    tHalfDays: 0.5,
    tMaxDays: 0.25,
    doseRef: 0.75,
    cmaxRef: 70,
    nativeUnit: 'pg/mL',
    typicalDoses: [0.5, 0.75, 1.5],
    defaultDose: 0.75,
    defaultFrequencyId: 'ed',
    window: E2_WINDOW,
    evidence: 'A',
    sources: ['EstroGel SmPC']
  }),
  F({
    id: 'e2-patch',
    compoundId: 'estradiol',
    name: 'Estradiolo cerotto matrix',
    cluster: 'estrogens',
    analyte: 'estradiol',
    analyteLabel: 'Estradiolo',
    route: 'td',
    model: 'zero-order',
    zeroOrderHours: 84,
    tHalfDays: 0.3,
    tMaxDays: 0.5,
    doseRef: 0.05,
    doseUnit: 'mg/die',
    cmaxRef: 50,
    nativeUnit: 'pg/mL',
    typicalDoses: [0.025, 0.05, 0.075, 0.1],
    defaultDose: 0.05,
    defaultFrequencyId: 'e3_5d',
    window: E2_WINDOW,
    evidence: 'A',
    notes: 'Dose come rilascio nominale mg/die; cambio ogni 3–4 giorni.',
    sources: ['Climara / Estradot SmPC']
  }),
  F({
    id: 'e2-valerate-im',
    compoundId: 'estradiol',
    name: 'Estradiolo valerato IM',
    cluster: 'estrogens',
    analyte: 'estradiol',
    analyteLabel: 'Estradiolo',
    route: 'im',
    tHalfDays: 3.5,
    tMaxDays: 1.5,
    doseRef: 10,
    cmaxRef: 400,
    nativeUnit: 'pg/mL',
    typicalDoses: [5, 10, 20],
    defaultDose: 10,
    defaultFrequencyId: 'e14d',
    window: E2_WINDOW,
    evidence: 'B',
    sources: ['Dusterberg & Nishino, estradiol valerate PK']
  }),
  F({
    id: 'e2-cypionate-im',
    compoundId: 'estradiol',
    name: 'Estradiolo cipionato IM',
    cluster: 'estrogens',
    analyte: 'estradiol',
    analyteLabel: 'Estradiolo',
    route: 'im',
    tHalfDays: 5,
    tMaxDays: 2,
    doseRef: 5,
    cmaxRef: 300,
    nativeUnit: 'pg/mL',
    typicalDoses: [2, 5],
    defaultDose: 5,
    defaultFrequencyId: 'e14d',
    window: E2_WINDOW,
    evidence: 'B',
    sources: ['Depo-Estradiol label']
  }),
  F({
    id: 'estriol-vaginal',
    compoundId: 'estriol',
    name: 'Estriolo vaginale',
    cluster: 'estrogens',
    analyte: 'estriol',
    analyteLabel: 'Estriolo',
    route: 'vaginal',
    tHalfDays: 0.5,
    tMaxDays: 0.08,
    doseRef: 0.5,
    cmaxRef: 150,
    nativeUnit: 'pg/mL',
    typicalDoses: [0.5],
    defaultDose: 0.5,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Ovestin SmPC']
  }),
  F({
    id: 'p4-oral',
    compoundId: 'progesterone',
    name: 'Progesterone micronizzato orale',
    brand: 'Utrogestan / Prometrium',
    cluster: 'progestins',
    analyte: 'progesterone',
    analyteLabel: 'Progesterone',
    route: 'oral',
    tHalfDays: 0.4,
    tMaxDays: 0.12,
    doseRef: 200,
    cmaxRef: 12,
    nativeUnit: 'ng/mL',
    typicalDoses: [100, 200],
    defaultDose: 200,
    defaultFrequencyId: 'ed',
    window: P4_WINDOW,
    evidence: 'A',
    sources: ['Utrogestan SmPC; metaboliti attivi (allopregnanolone)']
  }),
  F({
    id: 'p4-vaginal',
    compoundId: 'progesterone',
    name: 'Progesterone vaginale',
    cluster: 'progestins',
    analyte: 'progesterone',
    analyteLabel: 'Progesterone',
    route: 'vaginal',
    tHalfDays: 0.5,
    tMaxDays: 0.2,
    doseRef: 200,
    cmaxRef: 15,
    nativeUnit: 'ng/mL',
    typicalDoses: [100, 200],
    defaultDose: 200,
    defaultFrequencyId: 'ed',
    window: P4_WINDOW,
    evidence: 'A',
    sources: ['Crinone / Utrogestan vaginale']
  }),
  F({
    id: 'p4-im',
    compoundId: 'progesterone',
    name: 'Progesterone IM in olio',
    cluster: 'progestins',
    analyte: 'progesterone',
    analyteLabel: 'Progesterone',
    route: 'im',
    tHalfDays: 1.2,
    tMaxDays: 0.4,
    doseRef: 50,
    cmaxRef: 40,
    nativeUnit: 'ng/mL',
    typicalDoses: [25, 50, 100],
    defaultDose: 50,
    defaultFrequencyId: 'ed',
    window: P4_WINDOW,
    evidence: 'B',
    sources: ['Progesterone in oil USPI']
  }),
  F({
    id: 'dydrogesterone',
    compoundId: 'dydrogesterone',
    name: 'Didrogesterone',
    brand: 'Duphaston',
    cluster: 'progestins',
    analyte: 'dydrogesterone',
    analyteLabel: 'Didrogesterone',
    route: 'oral',
    tHalfDays: 0.3,
    tMaxDays: 0.06,
    doseRef: 10,
    cmaxRef: 20,
    nativeUnit: 'ng/mL',
    typicalDoses: [10, 20],
    defaultDose: 10,
    defaultFrequencyId: 'bid',
    evidence: 'A',
    sources: ['Duphaston SmPC']
  }),
  F({
    id: 'mpa-oral',
    compoundId: 'mpa',
    name: 'Medrossiprogesterone acetato orale',
    cluster: 'progestins',
    analyte: 'mpa',
    analyteLabel: 'MPA',
    route: 'oral',
    tHalfDays: 1.0,
    tMaxDays: 0.15,
    doseRef: 10,
    cmaxRef: 4,
    nativeUnit: 'ng/mL',
    typicalDoses: [5, 10],
    defaultDose: 10,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Provera label']
  }),
  F({
    id: 'mpa-depot',
    compoundId: 'mpa',
    name: 'Medrossiprogesterone depot',
    brand: 'Depo-Provera',
    cluster: 'progestins',
    analyte: 'mpa',
    analyteLabel: 'MPA',
    route: 'im',
    tHalfDays: 50,
    tMaxDays: 7,
    doseRef: 150,
    cmaxRef: 3.5,
    nativeUnit: 'ng/mL',
    typicalDoses: [150],
    defaultDose: 150,
    defaultFrequencyId: 'e84d',
    defaultDurationDays: 365,
    evidence: 'A',
    sources: ['Depo-Provera: ogni 12–13 settimane']
  }),
  F({
    id: 'cyproterone',
    compoundId: 'cyproterone',
    name: 'Ciproterone acetato',
    brand: 'Androcur',
    cluster: 'progestins',
    analyte: 'cyproterone',
    analyteLabel: 'Ciproterone',
    route: 'oral',
    tHalfDays: 1.6,
    tMaxDays: 0.15,
    doseRef: 50,
    cmaxRef: 250,
    nativeUnit: 'ng/mL',
    typicalDoses: [12.5, 25, 50],
    defaultDose: 25,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Androcur SmPC; t½ 38–42 h']
  }),
  F({
    id: 'hcg',
    compoundId: 'hcg',
    name: 'Gonadotropina corionica (hCG)',
    cluster: 'axis',
    analyte: 'hcg',
    analyteLabel: 'hCG',
    route: 'sc',
    tHalfDays: 1.5,
    tMaxDays: 0.5,
    doseRef: 1500,
    doseUnit: 'UI',
    cmaxRef: 80,
    nativeUnit: 'mIU/L',
    typicalDoses: [500, 1000, 1500, 2000, 5000],
    defaultDose: 1500,
    defaultFrequencyId: 'e3_5d',
    evidence: 'A',
    sources: ['Pregnyl / Gonasi: t½ ~24–36 h']
  }),
  F({
    id: 'anastrozole',
    compoundId: 'anastrozole',
    name: 'Anastrozolo',
    brand: 'Arimidex',
    cluster: 'axis',
    analyte: 'anastrozole',
    analyteLabel: 'Anastrozolo',
    route: 'oral',
    tHalfDays: 1.95,
    tMaxDays: 0.08,
    doseRef: 1,
    cmaxRef: 15,
    nativeUnit: 'ng/mL',
    typicalDoses: [0.25, 0.5, 1],
    defaultDose: 0.5,
    defaultFrequencyId: 'e3_5d',
    evidence: 'A',
    sources: ['Arimidex SmPC t½ ~46–48 h']
  }),
  F({
    id: 'letrozole',
    compoundId: 'letrozole',
    name: 'Letrozolo',
    brand: 'Femara',
    cluster: 'axis',
    analyte: 'letrozole',
    analyteLabel: 'Letrozolo',
    route: 'oral',
    tHalfDays: 2,
    tMaxDays: 0.08,
    doseRef: 2.5,
    cmaxRef: 35,
    nativeUnit: 'ng/mL',
    typicalDoses: [1.25, 2.5],
    defaultDose: 2.5,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Femara SmPC t½ ~2 d']
  }),
  F({
    id: 'exemestane',
    compoundId: 'exemestane',
    name: 'Exemestane',
    brand: 'Aromasin',
    cluster: 'axis',
    analyte: 'exemestane',
    analyteLabel: 'Exemestane',
    route: 'oral',
    tHalfDays: 1,
    tMaxDays: 0.08,
    doseRef: 25,
    cmaxRef: 17,
    nativeUnit: 'ng/mL',
    typicalDoses: [12.5, 25],
    defaultDose: 25,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Aromasin SmPC t½ ~24 h']
  }),
  F({
    id: 'tamoxifen',
    compoundId: 'tamoxifen',
    name: 'Tamoxifene',
    cluster: 'axis',
    analyte: 'tamoxifen',
    analyteLabel: 'Tamoxifene',
    route: 'oral',
    tHalfDays: 7,
    tMaxDays: 0.2,
    doseRef: 20,
    cmaxRef: 40,
    nativeUnit: 'ng/mL',
    typicalDoses: [10, 20],
    defaultDose: 20,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['t½ 5–7 d; metabolita endoxifene']
  }),
  F({
    id: 'clomiphene',
    compoundId: 'clomiphene',
    name: 'Clomifene citrato',
    cluster: 'axis',
    analyte: 'clomiphene',
    analyteLabel: 'Clomifene',
    route: 'oral',
    tHalfDays: 5,
    tMaxDays: 0.25,
    doseRef: 50,
    cmaxRef: 20,
    nativeUnit: 'ng/mL',
    typicalDoses: [25, 50],
    defaultDose: 25,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Enantiomeri zuclomifene (lungo) e enclomifene']
  }),
  F({
    id: 'enclomiphene',
    compoundId: 'enclomiphene',
    name: 'Enclomifene',
    cluster: 'axis',
    analyte: 'enclomiphene',
    analyteLabel: 'Enclomifene',
    route: 'oral',
    tHalfDays: 0.5,
    tMaxDays: 0.12,
    doseRef: 12.5,
    cmaxRef: 8,
    nativeUnit: 'ng/mL',
    typicalDoses: [12.5, 25],
    defaultDose: 12.5,
    defaultFrequencyId: 'ed',
    evidence: 'B',
    regulatory: 'off-label',
    sources: ['t½ ~10 h']
  }),
  F({
    id: 'finasteride',
    compoundId: 'finasteride',
    name: 'Finasteride',
    cluster: 'axis',
    analyte: 'finasteride',
    analyteLabel: 'Finasteride',
    route: 'oral',
    tHalfDays: 0.3,
    tMaxDays: 0.08,
    doseRef: 1,
    cmaxRef: 9,
    nativeUnit: 'ng/mL',
    typicalDoses: [1, 5],
    defaultDose: 1,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Propecia / Proscar SmPC']
  }),
  F({
    id: 'dutasteride',
    compoundId: 'dutasteride',
    name: 'Dutasteride',
    cluster: 'axis',
    analyte: 'dutasteride',
    analyteLabel: 'Dutasteride',
    route: 'oral',
    tHalfDays: 35,
    tMaxDays: 0.15,
    doseRef: 0.5,
    cmaxRef: 40,
    nativeUnit: 'ng/mL',
    typicalDoses: [0.5],
    defaultDose: 0.5,
    defaultFrequencyId: 'ed',
    defaultDurationDays: 180,
    evidence: 'A',
    sources: ['Avodart: t½ ~5 settimane a ss']
  }),
  F({
    id: 't4',
    compoundId: 'levothyroxine',
    name: 'Levotiroxina (T4)',
    cluster: 'thyroid',
    analyte: 't4',
    analyteLabel: 'T4 libera (proxy)',
    route: 'oral',
    tHalfDays: 7,
    tMaxDays: 0.12,
    doseRef: 100,
    doseUnit: 'µg',
    cmaxRef: 18,
    nativeUnit: 'pmol/L',
    typicalDoses: [25, 50, 75, 100, 125, 150],
    defaultDose: 100,
    defaultFrequencyId: 'ed',
    defaultDurationDays: 84,
    evidence: 'A',
    sources: ['t½ T4 ~7 giorni; ss in 4–6 settimane']
  }),
  F({
    id: 't3',
    compoundId: 'liothyronine',
    name: 'Liotironina (T3)',
    cluster: 'thyroid',
    analyte: 't3',
    analyteLabel: 'T3 libera (proxy)',
    route: 'oral',
    tHalfDays: 1,
    tMaxDays: 0.1,
    doseRef: 25,
    doseUnit: 'µg',
    cmaxRef: 8,
    nativeUnit: 'pmol/L',
    typicalDoses: [5, 10, 25],
    defaultDose: 10,
    defaultFrequencyId: 'bid',
    evidence: 'A',
    sources: ['t½ T3 ~1 giorno']
  }),
  F({
    id: 'semaglutide',
    compoundId: 'semaglutide',
    name: 'Semaglutide SC',
    brand: 'Ozempic / Wegovy',
    cluster: 'incretins',
    analyte: 'semaglutide',
    analyteLabel: 'Semaglutide',
    route: 'sc',
    tHalfDays: 7,
    tMaxDays: 2,
    doseRef: 1,
    doseUnit: 'mg',
    cmaxRef: 10,
    nativeUnit: 'ug/L',
    typicalDoses: [0.25, 0.5, 1, 1.7, 2.4],
    defaultDose: 1,
    defaultFrequencyId: 'weekly',
    defaultDurationDays: 168,
    evidence: 'A',
    sources: ['Ozempic SmPC t½ ~7 giorni']
  }),
  F({
    id: 'tirzepatide',
    compoundId: 'tirzepatide',
    name: 'Tirzepatide SC',
    brand: 'Mounjaro / Zepbound',
    cluster: 'incretins',
    analyte: 'tirzepatide',
    analyteLabel: 'Tirzepatide',
    route: 'sc',
    tHalfDays: 5,
    tMaxDays: 1.5,
    doseRef: 5,
    cmaxRef: 500,
    nativeUnit: 'ng/mL',
    typicalDoses: [2.5, 5, 7.5, 10, 12.5, 15],
    defaultDose: 5,
    defaultFrequencyId: 'weekly',
    defaultDurationDays: 168,
    evidence: 'A',
    sources: ['Mounjaro SmPC t½ ~5 giorni']
  }),
  F({
    id: 'liraglutide',
    compoundId: 'liraglutide',
    name: 'Liraglutide SC',
    brand: 'Saxenda / Victoza',
    cluster: 'incretins',
    analyte: 'liraglutide',
    analyteLabel: 'Liraglutide',
    route: 'sc',
    tHalfDays: 0.54,
    tMaxDays: 0.4,
    doseRef: 1.8,
    cmaxRef: 30,
    nativeUnit: 'ng/mL',
    typicalDoses: [0.6, 1.2, 1.8, 3],
    defaultDose: 1.8,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Victoza SmPC t½ ~13 h']
  }),
  F({
    id: 'somatropin',
    compoundId: 'somatropin',
    name: 'Somatropina (GH)',
    cluster: 'gh',
    analyte: 'gh',
    analyteLabel: 'GH',
    route: 'sc',
    tHalfDays: 0.15,
    tMaxDays: 0.16,
    doseRef: 1,
    doseUnit: 'mg',
    cmaxRef: 20,
    nativeUnit: 'ug/L',
    typicalDoses: [0.2, 0.4, 0.6, 1],
    defaultDose: 0.3,
    defaultFrequencyId: 'ed',
    evidence: 'A',
    sources: ['Genotropin SmPC; picco 3–6 h, t½ apparente breve']
  }),
  F({
    id: 'cjc-1295-no-dac',
    compoundId: 'cjc1295',
    name: 'CJC-1295 (no DAC) / Mod GRF 1-29',
    cluster: 'gh',
    analyte: 'cjc1295',
    analyteLabel: 'CJC-1295',
    route: 'sc',
    tHalfDays: 0.02,
    tMaxDays: 0.01,
    doseRef: 0.1,
    cmaxRef: 2,
    nativeUnit: 'ug/L',
    typicalDoses: [0.1, 0.2],
    defaultDose: 0.1,
    defaultFrequencyId: 'tid',
    evidence: 'C',
    regulatory: 'research',
    sources: ['PK stimata; t½ minuti senza DAC']
  }),
  F({
    id: 'ipamorelin',
    compoundId: 'ipamorelin',
    name: 'Ipamorelin',
    cluster: 'gh',
    analyte: 'ipamorelin',
    analyteLabel: 'Ipamorelin',
    route: 'sc',
    tHalfDays: 0.08,
    tMaxDays: 0.02,
    doseRef: 0.2,
    cmaxRef: 5,
    nativeUnit: 'ug/L',
    typicalDoses: [0.2, 0.3],
    defaultDose: 0.2,
    defaultFrequencyId: 'bid',
    evidence: 'C',
    regulatory: 'research',
    sources: ['t½ ~2 h, evidenza limitata']
  }),
  F({
    id: 'bpc-157',
    compoundId: 'bpc157',
    name: 'BPC-157',
    cluster: 'peptides',
    analyte: 'bpc157',
    analyteLabel: 'BPC-157',
    route: 'sc',
    tHalfDays: 0.02,
    tMaxDays: 0.01,
    doseRef: 0.25,
    cmaxRef: 1,
    nativeUnit: 'ug/L',
    typicalDoses: [0.25, 0.5],
    defaultDose: 0.25,
    defaultFrequencyId: 'ed',
    evidence: 'C',
    regulatory: 'research',
    notes: 'Nessuna PK umana robusta. Curva puramente illustrativa.',
    sources: ['Evidenza C — non usare per decisioni cliniche']
  }),
  F({
    id: 'rad140',
    compoundId: 'rad140',
    name: 'RAD-140 (Testolone)',
    cluster: 'sarms',
    analyte: 'rad140',
    analyteLabel: 'RAD-140',
    route: 'oral',
    tHalfDays: 2.5,
    tMaxDays: 0.2,
    doseRef: 10,
    cmaxRef: 200,
    nativeUnit: 'ng/mL',
    typicalDoses: [5, 10],
    defaultDose: 10,
    defaultFrequencyId: 'ed',
    evidence: 'C',
    regulatory: 'research',
    sources: ['Dati preclinici / community PK; evidenza C']
  })
]


